#!/usr/bin/env perl

use strict;
use FileHandle;

my $fh;
my @grid3_info;
my @apps;
my @app;
my $cluster;
my $path;

# Get GRID3_APP_DIR from the grid3-info.conf file.
if ($ARGV[0] && $ARGV[1]) {
    $path = $ARGV[0];
    $cluster= $ARGV[1];
} else {
    print "Usage: $0 <path to grid3-locations.txt file> <cluster_uid>\n";
    exit 1;
}
my $loc_file = "$path/grid3-locations.txt";
if(!-e $loc_file){
    exit 1;
}

#Get the Application Names from the grid3-locations file.
$fh = new FileHandle "$loc_file"
    or die "Can't open static ldif file: $loc_file\n";
@apps = <$fh>;


#Print out Results
foreach(@apps){
    chomp;
    @app = split / /;

    if(!defined $app[0] || !defined $app[1] || !defined $app[2]){
         next;
    }
    if($app[0] !~ m/^\#/){
       if($app[1]=~m/^$/ or $app[1]=~m/^\#/) {
          $app[1]='UNDEFINED';
       }
        print "dn: GlueLocationLocalID=$app[0],GlueSubClusterUniqueID=$cluster,GlueClusterUniqueID=$cluster,mds-vo-name=local,o=grid
objectClass: GlueClusterTop
objectClass: GlueLocation
objectClass: GlueSchemaVersion
objectClass: GlueKey
GlueLocationLocalID: $app[0]
GlueLocationName: $app[0]
GlueLocationVersion: $app[1]
GlueLocationPath: $app[2]
GlueChunkKey: GlueSubClusterUniqueID=$cluster
GlueSchemaVersionMajor: 1
GlueSchemaVersionMinor: 3
\n";
    }
}
print "\n";

exit 0;

