#!/usr/bin/env python

import re
import sys
import datetime

from test_common import *

CR = '\r'
LF = '\n'
CRLF = CR+LF

class LCG_InfoSites_closeSE:
    def __init__(self, base_path):
        self.cp = getConfig(base_path)
        self.bdii = self.cp.get("gip", "bdii_addr")
        self.opts = ['closeSE']
        try:
            self.vo = self.cp.get("gip", "vo")
        except:
            self.vo = "ops"


    def runquery(self):
        return runlcginfosites(self.bdii, self.vo, self.opts)


    def main(self):
        pout = self.runquery()
        output = pout.read().split(LF + LF)
        colorize = -1

        html = self.getHeader()
        for section in output:
            if len(section) > 10: # arbitrary number
                items = section.split(LF)
                if "Name" not in items[0]:
                    items.pop(0)

                ce = items.pop(0).split(":")[1].strip()
                for se in items:
                    html += self.getDetail(ce, se, colorize)
                    ce = ""
                colorize = colorize * -1

        html += self.getFooter()

        return html

    def getHeader(self):
        updateDateTime = datetime.datetime.now().strftime("%A %b %d %Y %H:%M:%S")

        html = """
            <h1>LCG InfoSites Query: 'lcg-infosites --is is.grid.iu.edu --vo ops closeSE'</h1>
            <h2>Last Updated on: %s </h2>
            <table rules='all' frame='border'>
            <tr>
                <th>CE</th>
                <th>Close SE</th>
            </tr>
        """

        return html % updateDateTime

    def getDetail(self, ce, se, colorize):
        if (colorize == -1):
            html = "      <tr style='background-color:#99ccff'>"
        else:
            html = "      <tr>"


        detail = """
                <td>%s</td>
                <td>%s</td>
            </tr>
        """
        return html + (detail % (ce, se))

    def getFooter(self):
        return "</table>"

if __name__ == '__main__':
    l = LCG_InfoSites_closeSE(sys.argv[1])
    print l.main()

