#!/usr/bin/env python

import re
import sys
import datetime

from test_common import *

CR = '\r'
LF = '\n'
CRLF = CR+LF

# lcg-info --list-se --vo ops --bdii is.grid.iu.edu:2170

class LCG_InfoSEList:
    def __init__(self, base_path):
        self.cp = getConfig(base_path)
        self.opt = "--list-se"
        self.bdii = self.cp.get("gip", "bdii_addr")
        self.port = self.cp.get("gip", "bdii_port")

    def runquery(self):
        return runlcginfo(self.opt, self.bdii, self.port):

    def main(self):
        pout = self.runquery()
        colorize = -1

        html = self.getHeader()
        for line in pout:
            if len(line) > 10: # arbitrary number
                se = line.split(":")[1].strip()
                html += self.getDetail(site, se, colorize)
                colorize = colorize * -1

        html += self.getFooter()

        return html

    def getHeader(self):
        updateDateTime = datetime.datetime.now().strftime("%A %b %d %Y %H:%M:%S")

        html = """
            <h1>LCG Info Query: 'lcg-info %s --vo ops --bdii %s:%s'</h1>
            <h2>Last Updated on: %s </h2>
            <table rules='all' frame='border'>
            <tr>
                <th>SE FQDN</th>
            </tr>
        """

        return html % (self.opt, self.bdii, self.port, updateDateTime)

    def getDetail(self, se, colorize):
        if (colorize == -1):
            html = "      <tr style='background-color:#99ccff'>"
        else:
            html = "      <tr>"


        detail = """
                <td>%s</td>
            </tr>
        """
        return html + (detail % se)

    def getFooter(self):
        return "</table>"

if __name__ == '__main__':
    l = LCG_InfoSEList(sys.argv[1])
    print l.main()

