#!/usr/bin/env python

info = """
dn: GlueVOInfoLocalID=pragma,GlueSALocalID=pragma,mds-vo-name=FNAL_GPFARM,o=grid
objectClass: GlueSATop
objectClass: GlueVOInfo
objectClass: GlueKey
objectClass: GlueSchemaVersion
GlueChunkKey: GlueSALocalID=pragma
GlueChunkKey: GlueSALocalID=pragma
GlueVOInfoLocalID: pragma
GlueVOInfoName: pragma
GlueVOInfoName: pragma
GlueVOInfoPath: pragma
GlueVOInfoPath: /grid/data
GlueVOInfoTag: UNAVAILABLE
GlueVOInfoTag: UNAVAILABLE
GlueVOInfoAccessControlBaseRule: pragma
GlueVOInfoAccessControlBaseRule: pragma
GlueSchemaVersionMajor: 1
GlueSchemaVersionMinor: 3
"""

print info

