#!/usr/bin/env python

import time

info = """
dn: GlueVOInfoLocalID=osgedu,GlueSALocalID=osgedu,mds-vo-name=FNAL_GPFARM,o=grid
objectClass: GlueSATop
objectClass: GlueVOInfo
objectClass: GlueKey
objectClass: GlueSchemaVersion
GlueChunkKey: GlueSALocalID=osgedu
GlueChunkKey: GlueSALocalID=osgedu
GlueVOInfoLocalID: osgedu
GlueVOInfoName: osgedu
GlueVOInfoName: osgedu
GlueVOInfoPath: osgedu
GlueVOInfoPath: /grid/data
GlueVOInfoTag: UNAVAILABLE
GlueVOInfoTag: UNAVAILABLE
GlueVOInfoAccessControlBaseRule: osgedu
GlueVOInfoAccessControlBaseRule: osgedu
GlueSchemaVersionMajor: 1
GlueSchemaVersionMinor: 3
"""

print info

time.sleep(15)

