#!/usr/bin/env python

import sys
import os

sys.path.insert(0, os.path.expandvars("$GIP_LOCATION/lib/python"))
sys.path.insert(1, os.path.expandvars("$GIP_LOCATION/reporting"))
from gip_testing import runTest, getTestConfig
from gip_validate import GipValidate

def main(args):
    """
    The main entry point for when dn_check is run in standalone mode.
    """
    cp = getTestConfig(args)
    cp.set("gip_tests", "validate_type", "bdii")

    runTest(cp, GipValidate)

if __name__ == '__main__':
    main(sys.argv)
