#!/usr/bin/env python

import re
import sys
import os

sys.path.insert(0, os.path.expandvars("$GIP_LOCATION/lib/python"))
import GipUnittest
from gip_common import getLogger, cp_get
from gip_testing import runTest, getTestConfig, runlcginfosites

class LcgInfoSitesCloseSE(GipUnittest.GipTestCase):
    def __init__(self, cp):
        GipUnittest.GipTestCase.__init__(self, 'testLcgInfoSitesCloseSE')
        self.bdii = cp_get(self.cp, "gip_tests", "bdii_addr", "")
        self.opts = ['closeSE']
        self.name = 'testLcgInfoSitesCloseSE'

    def testLcgInfoSitesCloseSE(self):
        """
LCG InfoSites Close SE Query

lcg-infosites --is is.grid.iu.edu --vo ops closeSE

Checks the BDII for close SE for the following vo's:  MIS, OPS, CMS,
and ATLAS.  NOTE: This test is not really intended for a site
adminitstrators other than to see if their site's CE and SE is
configured properly and is visible to VO's using the lcg tools.
        """
        vos = ['mis', 'ops', 'cms', 'atlas']
        for vo in vos:
            self.getInfoForVO(vo)

    def getInfoForVO(self, vo):
        pout = runlcginfosites(self.bdii, vo, self.opts).readlines()
        pout.pop(0) # Pop the header
        ce = " "
        results = {}
        template = "%-30s\t%-30s\n"
        output = "\n" + template % ("CE", "SE")
        first = True
        for line in pout:
            if line.startswith("Name"):
                first = True
                ce = line.split(":")[1].strip()
            else:
                if first:
                    first = False
                else:
                    ce = " "
                se = line.strip()
                if len(se) > 0:
                    output += template % (ce, se)

        self.expectTrue(False, output)

def main(args):
    cp = getTestConfig(args)
    runTest(cp, LcgInfoSitesCloseSE, per_site=False)

if __name__ == '__main__':
    main(sys.argv)
